const notes: Record<string, string[]> = {
  "book-editing": [
    "We read a sample and agree whether you need a structural edit, a line edit, or both.",
    "The manuscript is checked for plot or argument gaps before line-by-line work starts.",
    "The editor marks clarity, tone, and consistency while leaving your voice in place.",
    "You send notes on the marked file. We revise only the points you flag in that round.",
    "A last read clears leftover grammar and repeated terms before the file is called done.",
    "You receive the edited manuscript, ready for formatting or cover design.",
  ],
  "book-marketing": [
    "We learn the genre, the publication date, and the readers you want to reach.",
    "Comparable titles and categories are reviewed so the campaign fits the shelf you are on.",
    "The plan names the listing changes, the launch window, and what will not be included.",
    "Description, keywords, and categories are updated only after you approve the wording.",
    "Launch week follows the plan you signed, on accounts that stay in your name.",
    "After launch we note what sold and what should change on the listing.",
  ],
  "amazon-publishing": [
    "We confirm Kindle, paperback, or both, and that the KDP account is yours.",
    "Interior files are built to the trim and format Amazon expects for that edition.",
    "The cover is checked against page count and trim before it is attached.",
    "Description, categories, and keywords are entered for your review.",
    "Nothing is published until you accept the files and the listing fields.",
    "The edition goes live on your account, and royalties pay to you.",
  ],
  "audio-book-narration": [
    "We agree on tone, pace, and the sample you want to hear first.",
    "Names, places, and any words that must be pronounced a certain way are listed.",
    "The approved text is recorded in the voice you chose from the sample.",
    "You listen and mark lines that need another read.",
    "Those notes are recorded and the chapters are assembled into the final files.",
    "You receive the audio named in the agreement, ready for the platforms you listed.",
  ],
  "authors-website": [
    "We list the books, the bio, and the buy links the site has to show.",
    "Pages are mapped: home, books, about, and contact, plus any extra page you asked for.",
    "A layout is designed around your covers so you can approve it before build.",
    "You comment on type, order, and which retailer links belong on each book.",
    "The approved layout is built and checked on a phone and a desktop.",
    "The site goes live on a domain in your name, with a handoff so you can edit the basics.",
  ],
  "book-cover-design": [
    "We take the genre, the audience, and any covers you want to stand next to.",
    "Reference covers are chosen so the direction matches the shelf, not a random style.",
    "You see separate cover directions and pick the one to finish.",
    "That direction is the one we revise. A new concept is quoted on its own.",
    "Type, image, and spine are adjusted from your written notes.",
    "Print and ebook files are exported at the sizes in the agreement.",
  ],
  "book-formatting": [
    "Trim size, ebook format, and any images are confirmed before layout starts.",
    "Chapter styles, headings, and margins are set for that trim.",
    "The full manuscript is laid out so every chapter uses the same system.",
    "You review the pages and mark line breaks, headings, and image placement.",
    "Those marks are corrected on the designed pages, not only in the raw document.",
    "Print and ebook files are exported after you sign off.",
  ],
  "book-printing": [
    "Quantity, color or black-and-white, and binding are written down before a quote.",
    "Paper, trim, and cover finish are locked so the price matches the book.",
    "Approved interior and cover files are checked for bleed and spine width.",
    "Production waits until you accept those files.",
    "The agreed quantity is printed from the files you approved.",
    "Copies ship to the address in the order. Damaged copies from that run are replaced.",
  ],
  "children-book": [
    "Age range, format, and whether the book is a picture book or an early reader are set first.",
    "The text is edited for that age: length, vocabulary, and page turns.",
    "Illustration notes follow the story you approved, before final art is drawn.",
    "You review the art and the words together and mark what must change.",
    "Pages are laid out so pictures and text stay paired.",
    "Print and ebook files are prepared after you approve the pages.",
  ],
  "ebook-writing": [
    "Topic, reader, and word count are agreed before any chapter is drafted.",
    "An outline is written for your approval so the draft cannot wander.",
    "Chapters are written to that outline, in the length you set.",
    "You comment on examples, order, and anything that does not sound like you.",
    "The draft is edited for clarity and for headings an ebook can use.",
    "You receive the manuscript, ready for ebook formatting.",
  ],
  "fiction-writing": [
    "Genre, stakes, and the ending you want are discussed before pages are written.",
    "The outline locks characters and turns so the draft follows the story you described.",
    "Scenes are drafted from that outline, not from a different plot.",
    "You mark what should change in character, pace, or ending.",
    "The revision follows those notes and checks continuity.",
    "The finished manuscript is yours. Publishing is a separate stage.",
  ],
  "ghost-writing": [
    "We agree on the book type, the length, and how the interviews will run.",
    "Your stories and documents are recorded so the draft comes from you.",
    "An outline is built from those interviews for you to approve.",
    "Chapters are written in your voice from the approved outline.",
    "You revise facts, tone, and anything that should not be in the book.",
    "The manuscript is delivered in your name, with copyright staying with you.",
  ],
  "proof-reading": [
    "We confirm whether the proof is on the raw file or on the designed pages.",
    "The version you are about to publish is the one we read. Earlier drafts are not mixed in.",
    "Spelling, punctuation, names, and obvious layout slips are marked.",
    "You see every change and say which ones to keep.",
    "Accepted marks are cleaned on the file that will go to print or upload.",
    "You receive the corrected file and a short list of what changed.",
  ],
  "video-trailer": [
    "Length, where it will be posted, and the mood of the book are agreed first.",
    "On-screen lines are drafted from the book and approved before the cut.",
    "A first cut uses your cover and the approved lines.",
    "You mark pacing, text, and any image that does not belong.",
    "That round is recut. A new concept is outside this pass.",
    "The final file is exported for the channels named in the agreement.",
  ],
};

export function getServiceStepNotes(slug: string) {
  return notes[slug] ?? [];
}
